import Head from 'next/head'
//urql to make request
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from '../lib/query'

// Components
import Product from '../components/Product'


// Styles
import { Gallery } from '../styles/Gallery'

export default function Home() {

  // Fetch results from strapi
  const [results] = useQuery({query:PRODUCT_QUERY})
  const {data, fetching, error} = results

  // Display things depending of the fetching
  if(fetching)return<p>Loading...</p>
  if(error)return<p>Oh nooo... {error.message}</p>
  const products = data.products.data

  return (
    <div>
      <Head>
        <title>Jacker Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
        <Gallery>
          {products.map((product)=><Product product={product} key={product.attributes.slug}/>)}
        </Gallery>
      </main>
    </div>
  )
}
